### ISSUE TITLE
Model download permission.

### ISSUE THREAD

**Issue by demon-ling** [Bernard-Yang/CMN-ACL2023#1]
I am trying to obtain the model resources you provided, but Google Cloud Drive requires permission. Can you provide model download permission?

**Comment by demon-ling** [comment]
What dependency environment do I need to reproduce your code?

**Comment by Bernard-Yang** [comment]
Hi there,

Thanks for your interest. You can find the updated [link](https://drive.google.com/drive/folders/1efxSMLXBWKnxu6jDHbmZDFaBfTV5XJjc?usp=sharing) here. 

For the environment, you only need some basic packages, i.e., pytorch and transformers.
